export interface LandDetail {
  id: string;
  district: string;
  subDistrict: string;
  village: string;
  mOwnerNo: string;
  khasra: string;
  area: string;
}

export interface FarmerData {
  state?: string; // Add state to make it backwards compatible
  cardColor?: string;
  nameHindi: string;
  nameEnglish: string;
  dob: string;
  gender: string;
  mobile: string;
  aadhaar: string;
  farmerId: string;
  address: string;
  photoUrl: string;
  landDetails: LandDetail[];
  downloadDate: string;
}

export const BIHAR_DISTRICTS = [
  "Araria",
  "Arwal",
  "Aurangabad",
  "Banka",
  "Begusarai",
  "Bhagalpur",
  "Bhojpur",
  "Buxar",
  "Darbhanga",
  "East Champaran",
  "Gaya",
  "Gopalganj",
  "Jamui",
  "Jehanabad",
  "Kaimur",
  "Katihar",
  "Khagaria",
  "Kishanganj",
  "Lakhisarai",
  "Madhepura",
  "Madhubani",
  "Munger",
  "Muzaffarpur",
  "Nalanda",
  "Nawada",
  "Patna",
  "Purnia",
  "Rohtas",
  "Saharsa",
  "Samastipur",
  "Saran",
  "Sheikhpura",
  "Sheohar",
  "Sitamarhi",
  "Siwan",
  "Supaul",
  "Vaishali",
  "West Champaran",
].sort();

export const UP_DISTRICTS = [
  "Agra",
  "Aligarh",
  "Ambedkar Nagar",
  "Amethi",
  "Amroha",
  "Auraiya",
  "Ayodhya",
  "Azamgarh",
  "Baghpat",
  "Bahraich",
  "Ballia",
  "Balrampur",
  "Banda",
  "Barabanki",
  "Bareilly",
  "Basti",
  "Bhadohi",
  "Bijnor",
  "Budaun",
  "Bulandshahr",
  "Chandauli",
  "Chitrakoot",
  "Deoria",
  "Etah",
  "Etawah",
  "Farrukhabad",
  "Fatehpur",
  "Firozabad",
  "Gautam Buddha Nagar",
  "Ghaziabad",
  "Ghazipur",
  "Gonda",
  "Gorakhpur",
  "Hamirpur",
  "Hapur",
  "Hardoi",
  "Hathras",
  "Jalaun",
  "Jaunpur",
  "Jhansi",
  "Kannauj",
  "Kanpur Dehat",
  "Kanpur Nagar",
  "Kasganj",
  "Kaushambi",
  "Kheri",
  "Kushinagar",
  "Lalitpur",
  "Lucknow",
  "Maharajganj",
  "Mahoba",
  "Mainpuri",
  "Mathura",
  "Mau",
  "Meerut",
  "Mirzapur",
  "Moradabad",
  "Muzaffarnagar",
  "Pilibhit",
  "Pratapgarh",
  "Prayagraj",
  "Raebareli",
  "Rampur",
  "Saharanpur",
  "Sambhal",
  "Sant Kabir Nagar",
  "Shahjahanpur",
  "Shamli",
  "Shravasti",
  "Siddharthnagar",
  "Sitapur",
  "Sonbhadra",
  "Sultanpur",
  "Unnao",
  "Varanasi",
].sort();

export const MAHARASHTRA_DISTRICTS = [
  "Ahmednagar",
  "Akola",
  "Amravati",
  "Aurangabad",
  "Beed",
  "Bhandara",
  "Buldhana",
  "Chandrapur",
  "Dhule",
  "Gadchiroli",
  "Gondia",
  "Hingoli",
  "Jalgaon",
  "Jalna",
  "Kolhapur",
  "Latur",
  "Mumbai City",
  "Mumbai Suburban",
  "Nagpur",
  "Nanded",
  "Nandurbar",
  "Nashik",
  "Osmanabad",
  "Palghar",
  "Parbhani",
  "Pune",
  "Raigad",
  "Ratnagiri",
  "Sangli",
  "Satara",
  "Sindhudurg",
  "Solapur",
  "Thane",
  "Wardha",
  "Washim",
  "Yavatmal",
].sort();

export const MP_DISTRICTS = [
  "Agar Malwa",
  "Alirajpur",
  "Anuppur",
  "Ashoknagar",
  "Balaghat",
  "Barwani",
  "Betul",
  "Bhind",
  "Bhopal",
  "Burhanpur",
  "Chhatarpur",
  "Chhindwara",
  "Damoh",
  "Datia",
  "Dewas",
  "Dhar",
  "Dindori",
  "Guna",
  "Gwalior",
  "Harda",
  "Narmadapuram",
  "Indore",
  "Jabalpur",
  "Jhabua",
  "Katni",
  "Khandwa",
  "Khargone",
  "Mandla",
  "Mandsaur",
  "Morena",
  "Narsinghpur",
  "Neemuch",
  "Niwari",
  "Panna",
  "Raisen",
  "Rajgarh",
  "Ratlam",
  "Rewa",
  "Sagar",
  "Satna",
  "Sehore",
  "Seoni",
  "Shahdol",
  "Shajapur",
  "Sheopur",
  "Shivpuri",
  "Sidhi",
  "Singrauli",
  "Tikamgarh",
  "Ujjain",
  "Umaria",
  "Vidisha",
].sort();

export const RAJASTHAN_DISTRICTS = [
  "Ajmer",
  "Alwar",
  "Banswara",
  "Baran",
  "Barmer",
  "Bharatpur",
  "Bhilwara",
  "Bikaner",
  "Bundi",
  "Chittorgarh",
  "Churu",
  "Dausa",
  "Dholpur",
  "Dungarpur",
  "Hanumangarh",
  "Jaipur",
  "Jaisalmer",
  "Jalore",
  "Jhalawar",
  "Jhunjhunu",
  "Jodhpur",
  "Karauli",
  "Kota",
  "Nagaur",
  "Pali",
  "Pratapgarh",
  "Rajsamand",
  "Sawai Madhopur",
  "Sikar",
  "Sirohi",
  "Sri Ganganagar",
  "Tonk",
  "Udaipur",
].sort();

export const KERALA_DISTRICTS = [
  "Alappuzha",
  "Ernakulam",
  "Idukki",
  "Kannur",
  "Kasaragod",
  "Kollam",
  "Kottayam",
  "Kozhikode",
  "Malappuram",
  "Palakkad",
  "Pathanamthitta",
  "Thiruvananthapuram",
  "Thrissur",
  "Wayanad",
].sort();

export const CHHATTISGARH_DISTRICTS = [
  "Balod",
  "Baloda Bazar",
  "Balrampur",
  "Bastar",
  "Bemetara",
  "Bijapur",
  "Bilaspur",
  "Dantewada",
  "Dhamtari",
  "Durg",
  "Gariaband",
  "Gaurela Pendra Marwahi",
  "Janjgir-Champa",
  "Jashpur",
  "Kabirdham",
  "Kanker",
  "Kondagaon",
  "Khairagarh Chhuikhadan Gandai",
  "Korba",
  "Koriya",
  "Mahasamund",
  "Manendragarh Chirmiri Bharatpur",
  "Mohla Manpur Ambagarh Chouki",
  "Mungeli",
  "Narayanpur",
  "Raigarh",
  "Raipur",
  "Rajnandgaon",
  "Sakti",
  "Sarangarh Bilaigarh",
  "Sukma",
  "Surajpur",
  "Surguja",
].sort();

export const TAMIL_NADU_DISTRICTS = [
  "Ariyalur",
  "Chengalpattu",
  "Chennai",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kallakurichi",
  "Kanchipuram",
  "Kanyakumari",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Mayiladuthurai",
  "Nagapattinam",
  "Namakkal",
  "Nilgiris",
  "Perambalur",
  "Pudukkottai",
  "Ramanathapuram",
  "Ranipet",
  "Salem",
  "Sivaganga",
  "Tenkasi",
  "Thanjavur",
  "Theni",
  "Thoothukudi",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tiruppur",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruvarur",
  "Vellore",
  "Viluppuram",
  "Virudhunagar",
].sort();

export const GUJARAT_DISTRICTS = [
  "Ahmedabad",
  "Amreli",
  "Anand",
  "Banaskantha",
  "Bharuch",
  "Bhavnagar",
  "Dahod",
  "Dang",
  "Gandhinagar",
  "Jamnagar",
  "Junagadh",
  "Kutch",
  "Kheda",
  "Mehsana",
  "Narmada",
  "Navsari",
  "Panchmahal",
  "Patan",
  "Porbandar",
  "Rajkot",
  "Sabarkantha",
  "Surat",
  "Surendranagar",
  "Tapi",
  "Vadodara",
  "Valsad",
  "Botad",
  "Chhota Udepur",
  "Devbhumi Dwarka",
  "Gir Somnath",
  "Mahisagar",
  "Morbi",
  "Aravali",
].sort();

export const HARYANA_DISTRICTS = [
  "Ambala",
  "Bhiwani",
  "Charkhi Dadri",
  "Faridabad",
  "Fatehabad",
  "Gurugram",
  "Hisar",
  "Jhajjar",
  "Jind",
  "Kaithal",
  "Karnal",
  "Kurukshetra",
  "Mahendragarh",
  "Nuh",
  "Palwal",
  "Panchkula",
  "Panipat",
  "Rewari",
  "Rohtak",
  "Sirsa",
  "Sonipat",
  "Yamunanagar",
].sort();

export const PUNJAB_DISTRICTS = [
  "Amritsar",
  "Barnala",
  "Bathinda",
  "Faridkot",
  "Fatehgarh Sahib",
  "Fazilka",
  "Ferozepur",
  "Gurdaspur",
  "Hoshiarpur",
  "Jalandhar",
  "Kapurthala",
  "Ludhiana",
  "Malerkotla",
  "Mansa",
  "Moga",
  "Muktsar",
  "Pathankot",
  "Patiala",
  "Rupnagar",
  "Sahibzada Ajit Singh Nagar",
  "Sangrur",
  "Shahid Bhagat Singh Nagar",
  "Tarn Taran",
].sort();

export const ANDHRA_PRADESH_DISTRICTS = [
  "Anantapur",
  "Chittoor",
  "East Godavari",
  "Guntur",
  "Krishna",
  "Kurnool",
  "Prakasam",
  "Srikakulam",
  "Sri Potti Sriramulu Nellore",
  "Visakhapatnam",
  "Vizianagaram",
  "West Godavari",
  "YSR Kadapa",
  "Parvathipuram Manyam",
  "Alluri Sitharama Raju",
  "Anakapalli",
  "Kakinada",
  "Konaseema",
  "Eluru",
  "NTR",
  "Bapatla",
  "Palnadu",
  "Nandyal",
  "Sri Sathya Sai",
  "Annamayya",
  "Tirupati",
].sort();

export const ASSAM_DISTRICTS = [
  "Baksa",
  "Barpeta",
  "Biswanath",
  "Bongaigaon",
  "Cachar",
  "Charaideo",
  "Chirang",
  "Darrang",
  "Dhemaji",
  "Dhubri",
  "Dibrugarh",
  "Dima Hasao",
  "Goalpara",
  "Golaghat",
  "Hailakandi",
  "Jorhat",
  "Kamrup",
  "Kamrup Metropolitan",
  "Karbi Anglong",
  "Karimganj",
  "Kokrajhar",
  "Lakhimpur",
  "Majuli",
  "Morigaon",
  "Nagaon",
  "Nalbari",
  "Sivasagar",
  "Sonitpur",
  "South Salmara-Mankachar",
  "Tinsukia",
  "Udalguri",
  "West Karbi Anglong",
  "Bajali",
  "Tamulpur",
].sort();

export const ODISHA_DISTRICTS = [
  "Angul",
  "Boudh",
  "Balangir",
  "Bargarh",
  "Balasore",
  "Bhadrak",
  "Cuttack",
  "Deogarh",
  "Dhenkanal",
  "Ganjam",
  "Gajapati",
  "Jharsuguda",
  "Jajpur",
  "Jagatsinghpur",
  "Khordha",
  "Keonjhar",
  "Kalahandi",
  "Kandhamal",
  "Koraput",
  "Kendrapara",
  "Malkangiri",
  "Mayurbhanj",
  "Nabarangpur",
  "Nuapada",
  "Nayagarh",
  "Puri",
  "Rayagada",
  "Sambalpur",
  "Subarnapur",
  "Sundargarh",
].sort();

export const JHARKHAND_DISTRICTS = [
  "Bokaro",
  "Chatra",
  "Deoghar",
  "Dhanbad",
  "Dumka",
  "East Singhbhum",
  "Garhwa",
  "Giridih",
  "Godda",
  "Gumla",
  "Hazaribagh",
  "Jamtara",
  "Khunti",
  "Koderma",
  "Latehar",
  "Lohardaga",
  "Pakur",
  "Palamu",
  "Ramgarh",
  "Ranchi",
  "Sahibganj",
  "Seraikela Kharsawan",
  "Simdega",
  "West Singhbhum",
].sort();

export const TELANGANA_DISTRICTS = [
  "Adilabad",
  "Bhadradri Kothagudem",
  "Hanamkonda",
  "Hyderabad",
  "Jagtial",
  "Jangaon",
  "Jayashankar Bhupalpally",
  "Jogulamba Gadwal",
  "Kamareddy",
  "Karimnagar",
  "Khammam",
  "Kumuram Bheem Asifabad",
  "Mahabubabad",
  "Mahabubnagar",
  "Mancherial",
  "Medak",
  "Medchal-Malkajgiri",
  "Mulugu",
  "Nagarkurnool",
  "Nalgonda",
  "Narayanpet",
  "Nirmal",
  "Nizamabad",
  "Peddapalli",
  "Rajanna Sircilla",
  "Rangareddy",
  "Sangareddy",
  "Siddipet",
  "Suryapet",
  "Vikarabad",
  "Wanaparthy",
  "Warangal",
  "Yadadri Bhuvanagiri",
].sort();

export const BIHAR_SUB_DISTRICTS: Record<string, string[]> = {
  Araria: [
    "Araria",
    "Forbesganj",
    "Jokihat",
    "Kursakanta",
    "Palasi",
    "Raniganj",
    "Sikakti",
    "Bhargama",
    "Narpatganj",
  ],
  Arwal: ["Arwal", "Kaler", "Karpi", "Kurtha", "Sonbhadra Banshi Suryapur"],
  Aurangabad: [
    "Aurangabad",
    "Barun",
    "Daudnagar",
    "Deo",
    "Goh",
    "Haspura",
    "Kutumba",
    "Madanpur",
    "Nabinagar",
    "Obra",
    "Rafiganj",
  ],
  Banka: [
    "Banka",
    "Amarpur",
    "Bausi",
    "Belhar",
    "Chanan",
    "Dhoraiya",
    "Fullidumar",
    "Katoriya",
    "Panchrukhi",
    "Rajoun",
    "Shambhuganj",
  ],
  Begusarai: [
    "Begusarai",
    "Bakhri",
    "Ballia",
    "Barauni",
    "Bhagwanpur",
    "Cheria Bariarpur",
    "Chhorahi",
    "Garhpura",
    "Khodawandpur",
    "Mansurchak",
    "Matihani",
    "Naokothi",
    "Sahebpur Kamal",
    "Shamho Akurha",
    "Teghra",
  ],
  Bhagalpur: [
    "Bhagalpur",
    "Gopalpur",
    "Goradih",
    "Ismailpur",
    "Jagdishpur",
    "Kahalgaon",
    "Kharik",
    "Narayanpur",
    "Nathnagar",
    "Pirpainti",
    "Rangrachowk",
    "Sabour",
    "Shahkund",
    "Sultanganj",
  ],
  Bhojpur: [
    "Arrah",
    "Agiaon",
    "Barhara",
    "Bihiya",
    "Charpokhari",
    "Garhani",
    "Jagdishpur",
    "Koilwar",
    "Piro",
    "Sahar",
    "Sandesh",
    "Shahpur",
    "Tarari",
    "Udwantnagar",
  ],
  Buxar: [
    "Buxar",
    "Brahmpur",
    "Chakki",
    "Chausa",
    "Dumraon",
    "Itarhi",
    "Nawanagar",
    "Rajpur",
    "Simri",
  ],
  Darbhanga: [
    "Darbhanga",
    "Alinagar",
    "Bahadurpur",
    "Baheri",
    "Biraul",
    "Ghanshyampur",
    "Hanuman Nagar",
    "Hayaghat",
    "Jale",
    "Keoti",
    "Kiratpur",
    "Kushmeshwar Asthan",
    "Kushmeshwar Asthan East",
    "Singhwara",
    "Tardih",
  ],
  "East Champaran": [
    "Motihari",
    "Adapur",
    "Areraj",
    "Banjaria",
    "Chakia",
    "Chiraia",
    "Dhaka",
    "Ghorasahan",
    "Harsidhi",
    "Kesaria",
    "Madhuban",
    "Mehsi",
    "Paharpur",
    "Pakri Dayal",
    "Phenhara",
    "Piprakothi",
    "Ramgarhwa",
    "Raxaul",
    "Sangrampur",
    "Sugauli",
    "Turkaulia",
  ],
  Gaya: [
    "Gaya Sadar",
    "Amas",
    "Atri",
    "Bankey Bazar",
    "Barachatti",
    "Belaganj",
    "Bodh Gaya",
    "Dobhi",
    "Dumaria",
    "Fatehpur",
    "Guraru",
    "Gurua",
    "Imamganj",
    "Khizirsarai",
    "Konch",
    "Manpur",
    "Mohanpur",
    "Muhra",
    "Neem Chak Bathani",
    "Paraiya",
    "Sherghati",
    "Tan Kuppa",
    "Tickari",
    "Wazirganj",
  ],
  Gopalganj: [
    "Gopalganj",
    "Baikunthpur",
    "Barauli",
    "Bhorey",
    "Hathua",
    "Kuchaikote",
    "Manjha",
    "Panchdeori",
    "Phulwariya",
    "Sidhwalia",
    "Thawe",
    "Uchka Gaon",
    "Vijayipur",
  ],
  Jamui: [
    "Jamui",
    "Barhat",
    "Chakai",
    "Gidhaur",
    "Isklampur",
    "Jhajha",
    "Khaira",
    "Laxmipur",
    "Sono",
  ],
  Jehanabad: [
    "Jehanabad",
    "Ghoshi",
    "Hulasganj",
    "Kako",
    "Modanganj",
    "Makhdumpur",
    "Ratni Faridpur",
  ],
  Kaimur: [
    "Bhabua",
    "Adhaura",
    "Chainpur",
    "Chand",
    "Durgawati",
    "Kudra",
    "Mohania",
    "Ramgarh",
    "Rampur",
    "Rohtas",
  ],
  Katihar: [
    "Katihar",
    "Amdabad",
    "Azamnagar",
    "Balrampur",
    "Barari",
    "Barsoi",
    "Dandkhora",
    "Falka",
    "Hasanganj",
    "Kadwa",
    "Korha",
    "Kursela",
    "Manihari",
    "Mansahi",
    "Pranpur",
    "Sameli",
  ],
  Khagaria: [
    "Khagaria",
    "Alauli",
    "Beldaur",
    "Chautham",
    "Gogri",
    "Mansi",
    "Parbatta",
  ],
  Kishanganj: [
    "Kishanganj",
    "Bahadurganj",
    "Dighalbank",
    "Kochadhaman",
    "Pothia",
    "Terhagachh",
    "Thakurganj",
  ],
  Lakhisarai: [
    "Lakhisarai",
    "Barahiya",
    "Chanan",
    "Halsi",
    "Pipariya",
    "Ramgarh Chowk",
    "Surajgarha",
  ],
  Madhepura: [
    "Madhepura",
    "Alamnagar",
    "Bihariganj",
    "Chausa",
    "Gwalpara",
    "Kishanganj",
    "Kumarkhand",
    "Murliganj",
    "Puraini",
    "Singheshwar",
    "Udakishanganj",
  ],
  Madhubani: [
    "Madhubani",
    "Andhratharhi",
    "Babubarhi",
    "Basopatti",
    "Benipatti",
    "Bisfi",
    "Ghoghardiha",
    "Harlakhi",
    "Jainagar",
    "Jhanjharpur",
    "Kaluahi",
    "Khajauli",
    "Khutauna",
    "Ladania",
    "Lakhnaur",
    "Madhepur",
    "Pandaul",
    "Phulparas",
    "Rajnagar",
    "Sahatwar",
  ],
  Munger: [
    "Munger",
    "Bariarpur",
    "Dharhara",
    "Haveli Kharagpur",
    "Jamalpur",
    "Sangrampur",
    "Tarapur",
    "Tetia Bambar",
  ],
  Muzaffarpur: [
    "Muzaffarpur",
    "Aurai",
    "Bandra",
    "Baruraj",
    "Bochahan",
    "Gaighat",
    "Kanti",
    "Katra",
    "Kurhani",
    "Marwan",
    "Minapur",
    "Motipur",
    "Musahari",
    "Paroo",
    "Sahebganj",
    "Sakra",
    "Saraiya",
  ],
  Nalanda: [
    "Bihar Sharif",
    "Asthawan",
    "Ben",
    "Bind",
    "Chandi",
    "Ekangarsarai",
    "Giriak",
    "Harnaut",
    "Hilsa",
    "Islampur",
    "Karai Parsurai",
    "Katrisarai",
    "Nagarnausa",
    "Noorsarai",
    "Parwalpur",
    "Rahui",
    "Rajgir",
    "Sarabera",
    "Silao",
    "Tharthari",
  ],
  Nawada: [
    "Nawada",
    "Akbarpur",
    "Govindpur",
    "Hisua",
    "Kashichak",
    "Kauwacol",
    "Meskaur",
    "Narhat",
    "Pakribarawan",
    "Rajauli",
    "Roh",
    "Sirdala",
    "Warisaliganj",
  ],
  Patna: [
    "Patna Sadar",
    "Anisabad",
    "Athmalgola",
    "Bakhtiyarpur",
    "Barh",
    "Belchhi",
    "Bihta",
    "Bikram",
    "Danapur",
    "Daniyawan",
    "Dulhin Bazar",
    "Fatwah",
    "Ghoswari",
    "Khagaul",
    "Khusrupur",
    "Masaurhi",
    "Mokama",
    "Naubatpur",
    "Paliganj",
    "Pandarak",
    "Phulwari Sharif",
    "Punpun",
    "Sampatchak",
  ],
  Purnia: [
    "Purnia",
    "Amour",
    "Baisi",
    "Banmankhi",
    "Bhawanipur",
    "Dagarua",
    "Dhamdaha",
    "Jalalgadh",
    "Kasba",
    "Krityanand Nagar",
    "Purnia East",
    "Rupauli",
    "Srinagar",
  ],
  Rohtas: [
    "Sasaram",
    "Akhorigola",
    "Banjari",
    "Chenari",
    "Dawath",
    "Dehri",
    "Dinara",
    "Karakat",
    "Kochas",
    "Nasriganj",
    "Nauhatta",
    "Nokha",
    "Rajpur",
    "Rohtas",
    "Sanjhauli",
    "Sheosagar",
    "Suryapura",
    "Tilouthu",
  ],
  Saharsa: [
    "Banma Itahri",
    "Kahra",
    "Mahishi",
    "Nauhatta",
    "Patarghat",
    "Salkhua",
    "Satar Kataiya",
    "Saurbazar",
    "Simri Bakhtiarpur",
    "Sonbarsa",
  ],
  Samastipur: [
    "Samastipur",
    "Bibhutipur",
    "Bithan",
    "Dalsinghsarai",
    "Hasanpur",
    "Kalyanpur",
    "Khanpur",
    "Mohanpur",
    "Mohiuddin Nagar",
    "Morwa",
    "Patori",
    "Pusa",
    "Rosera",
    "Sarairanjan",
    "Shivaji Nagar",
    "Singhia",
    "Tajpur",
    "Ujiarpur",
    "Warisnagar",
  ],
  Saran: [
    "Chhapra",
    "Amnour",
    "Baniapur",
    "Dariapur",
    "Dighwara",
    "Ekma",
    "Garkha",
    "Isuapur",
    "Jalalpur",
    "Lahladpur",
    "Mashrakh",
    "Nagra",
    "Panapur",
    "Parsa",
    "Revelganj",
    "Sonepur",
    "Taraiya",
  ],
  Sheikhpura: [
    "Sheikhpura",
    "Ariari",
    "Barbigha",
    "Chewara",
    "Ghat Kusumbha",
    "Shekhopur Sarai",
  ],
  Sheohar: ["Sheohar", "Dumri Katsari", "Piprarhi", "Purnahiya", "Tariyani"],
  Sitamarhi: [
    "Sitamarhi",
    "Bairgania",
    "Bajpatti",
    "Bathnaha",
    "Belsand",
    "Bokhra",
    "Choraut",
    "Dumra",
    "Majorganj",
    "Nanpur",
    "Parihar",
    "Parsauni",
    "Pupri",
    "Riga",
    "Runni Saidpur",
    "Sonbarsa",
    "Suppi",
    "Sursand",
  ],
  Siwan: [
    "Siwan",
    "Andar",
    "Barharia",
    "Basantpur",
    "Bhagwanpur Hat",
    "Darauli",
    "Daraunda",
    "Gautam Budh Nagar",
    "Gopalpur",
    "Guraiakothi",
    "Hasanpura",
    "Hussainganj",
    "Lakri Nabiganj",
    "Maharajganj",
    "Mairwa",
    "Nautan",
    "Panchrukhi",
    "Raghunathpur",
    "Siswan",
    "Ziradei",
  ],
  Supaul: [
    "Supaul",
    "Basantpur",
    "Chhatapur",
    "Kishanpur",
    "Marauna",
    "Nirmali",
    "Pipra",
    "Raghopur",
    "Saraigarh Bhaptiyahi",
    "Tribeniganj",
  ],
  Vaishali: [
    "Hajipur",
    "Bhagwanpur",
    "Bidupur",
    "Chehra Kalan",
    "Desri",
    "Garaul",
    "Jandaha",
    "Lalganj",
    "Mahnar",
    "Mahua",
    "Patedhi Belsar",
    "Patepur",
    "Raghopur",
    "Raja Pakar",
    "Sahdei Buzurg",
    "Vaishali",
  ],
  "West Champaran": [
    "Bettiah",
    "Bagaha-1",
    "Bagaha-2",
    "Bairia",
    "Chanpatia",
    "Gaunaha",
    "Jogapatti",
    "Lauriya",
    "Mainatand",
    "Majhaulia",
    "Narkatiaganj",
    "Nautan",
    "Piprasi",
    "Ramnagar",
    "Sikta",
    "Thakrahan",
    "Yogapatti",
  ],
};

export const INITIAL_FARMER_DATA: FarmerData = {
  state: "Bihar",
  cardColor: "",
  nameHindi: "किसान का नाम",
  nameEnglish: "Farmer Name",
  dob: "01/01/2026",
  gender: "Male",
  mobile: "7070200199",
  aadhaar: "000000000000",
  farmerId: "000-00-00-00-00",
  address: "",
  photoUrl: "https://picsum.photos/200/200",
  downloadDate: "0",
  landDetails: [
    {
      id: "1",
      district: "",
      subDistrict: "",
      village: "",
      mOwnerNo: "",
      khasra: "",
      area: "",
    },
  ],
};
